language: node_js
node_js:
  - 12

addons:
chrome: stable

cache:
yarn: true
directories:
  - $HOME/node_modules
  - $HOME/backend/node_modules
  - $HOME/frontend/node_modules

env:
  - SCRIPT=backend-lint:format
  - SCRIPT=frontend-lint:format

before_install:
  - yarn install
  - cd $HOME/frontend
  - yarn install
  - cd ..
  - cd $HOME/backend
  - yarn install
  - cd ..

script:
  - yarn prettify
  - yarn $SCRIPT
