language: node_js
os:
  - linux
  - windows
  - osx

node_js:
  - 12

addons:
chrome: stable

cache:
yarn: true
directories:
  - node_modules
  - backend/node_modules
  - frontend/node_modules

env:
  global:
    - YARN_GPG=no
  jobs:
    - JS_SCRIPT=b-build:js TEST_SCRIPT=b-build:test
    - JS_SCRIPT=f-build:js TEST_SCRIPT=f-build:test

before_install:
  - yarn install
  - cd frontend
  - yarn install
  - cd ..
  - cd backend
  - yarn install
  - cd ..

script:
  - yarn $JS_SCRIPT
  - yarn $TEST_SCRIPT
