language: node_js
os:
  - linux
  - windows
  - osx
  
node_js:
  - 12

addons:
chrome: stable

cache:
yarn: true
directories:
  - node_modules
  - backend/node_modules
  - frontend/node_modules

env:
  global:
    - YARN_GPG=no
  local:
    - SCRIPT=backend-lint:check
    - SCRIPT=frontend-lint:check

before_install:
  - yarn install
  - cd frontend
  - yarn install
  - cd ..
  - cd backend
  - yarn install
  - cd ..

script:
  - yarn prettify
  - yarn $SCRIPT
